"""T1 质量过滤模块单测：覆盖 5 类拒因 + 双信号去重。"""

from __future__ import annotations

import pytest

from prompt_help.core import quality
from prompt_help.core.quality import QualityConfig, is_quality_prompt


@pytest.fixture
def qc() -> QualityConfig:
    return QualityConfig()


# ---------------------------------------------------------------------------
# 长度 / 噪声前缀
# ---------------------------------------------------------------------------

def test_too_short_rejected(qc):
    passed, reason = is_quality_prompt("hi", qc)
    assert not passed and "too_short" in reason


def test_too_long_rejected(qc):
    passed, reason = is_quality_prompt("a" * 10000, qc)
    assert not passed and "too_long" in reason


def test_slash_command_rejected(qc):
    passed, reason = is_quality_prompt("/prompt-save", qc)
    assert not passed


def test_system_reminder_rejected(qc):
    passed, reason = is_quality_prompt(
        "<system-reminder>" + "x" * 200 + "</system-reminder>", qc,
    )
    assert not passed and reason == "noise_prefix"


def test_image_prefix_rejected(qc):
    passed, reason = is_quality_prompt("[Image #2]" + "x" * 200, qc)
    assert not passed and reason == "noise_prefix"


def test_image_only_body_rejected(qc):
    """主体只有 [Image: source: ...] 的（图片附件粘贴）→ 拒。"""
    text = (
        "[Image: source: C:\\Users\\lin\\.claude\\image-cache\\xxx\\1.png]\n"
        "[Image: source: C:\\Users\\lin\\.claude\\image-cache\\xxx\\2.png]"
    )
    passed, reason = is_quality_prompt(text, qc)
    assert not passed and reason == "image_attachment_only"


def test_powershell_stderr_paste_rejected(qc):
    """PowerShell 错误粘贴（At D:\\..., FullyQualifiedErrorId, ParserError, PowerShell return code）"""
    text = (
        "At D:\\Dev\\ClaudeBackup\\scripts\\elevate_deploy.ps1:41 char:24\n"
        "+ Read-Host \"按任意键退出\"\n"
        "+   ~~~~~~~~~~~~~~~~~~~~~~~~~~\n"
        "The string is missing the terminator: \". At D:\\Dev\\ClaudeBackup\\scripts\\elevate_deploy.ps1:35 char:12\n"
        "+ } else {\n"
        "Missing closing '}' in statement block or type definition. At D:\\Dev\\ClaudeBackup\\scripts\\elevate_deploy.ps1:30 char:8\n"
        "+ } else {\n"
        "Missing closing '}' in statement block or type definition.\n"
        "+ CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException\n"
        "+ FullyQualifiedErrorId : TerminatorExpectedAtEndOfString\n"
        "[cmd] PowerShell return code = 1 [cmd] Press any key to close..."
    )
    passed, reason = is_quality_prompt(text, qc)
    assert not passed and reason == "error_log_paste"


def test_cc_caveat_envelope_rejected(qc):
    """Claude Code 跑 !command 时注入的 Caveat envelope。"""
    text = (
        "Caveat: The messages below were generated by the user while running "
        "local commands. DO NOT respond to these messages or otherwise "
        "consider them in your response unless the user explicitly asks you to."
    )
    passed, reason = is_quality_prompt(text, qc)
    assert not passed
    assert reason in ("noise_prefix", "tool_meta_injection")


def test_local_command_stdout_rejected(qc):
    text = (
        "<local-command-stdout>\n"
        "fake output goes here\n"
        "lots of more output content\n"
        "</local-command-stdout>"
    )
    # 即使加额外内容也得被识别
    text = text + "\n" + "x" * 200
    passed, reason = is_quality_prompt(text, qc)
    assert not passed and reason == "noise_prefix"


def test_node_error_paste_rejected(qc):
    """Node.js ENOENT 错误 + 微信小程序日志 → 拒。"""
    text = (
        "message: 真机调试 Error: ENOENT: no such file or directory, "
        "open 'D:/My_Project/MinPEI/minbei-heritage-miniprogram/components/bottom-nav/bottom-nav.wxml' "
        "File: components/bottom-nav/bottom-nav.wxml appid: wxd5cc2b36a853fcc5 "
        "openid: o6zAJs5ZBSyfObaySIKzLjBw-ApA ideVersion: 2.01.2510290 osType: win32-x64 "
        "time: 2026-05-07 10:45:45 这是不行，你到底怎么改的？"
    )
    passed, reason = is_quality_prompt(text, qc)
    assert not passed and reason == "error_log_paste"


# ---------------------------------------------------------------------------
# Mojibake / shell 日志检测
# ---------------------------------------------------------------------------

def test_powershell_error_dump_rejected(qc):
    text = (
        "'NoProfile' 不是内部或外部命令，也不是可运行的程序 或批处理文件。 "
        "'xe' (' 不是内部或外部命令，也不是可运行的程序 或批处理文件。 "
        "'log:' 不是内部或外部命令，也不是可运行的程序 或批处理文件。 "
        + "x" * 100
    )
    passed, reason = is_quality_prompt(text, qc)
    assert not passed and reason == "mojibake_or_log_dump"


def test_repeated_phrase_rejected(qc):
    """同一短语重复占据文本绝大部分 → log dump。"""
    text = "ABCDEFGHIJ" * 50  # 单一 10 字模式重复 50 次
    passed, reason = is_quality_prompt(text, qc)
    assert not passed and reason == "mojibake_or_log_dump"


# ---------------------------------------------------------------------------
# 一次性调试指令检测
# ---------------------------------------------------------------------------

def test_oneoff_debug_with_path_and_id_rejected(qc):
    text = (
        "看 v1.6 e2e pipeline 日志（task b7a5nv6zh）。"
        "读 C:\\Users\\lin\\AppData\\Local\\Temp\\claude\\D--My-Project-Likner-SGO-sgo-mainline"
        "\\692948b9-5a3c\\tasks\\b7a5nv6zh.output 的最近 50 行确认进度。"
    )
    passed, reason = is_quality_prompt(text, qc)
    assert not passed and reason == "oneoff_debug_instruction"


def test_long_template_with_few_signals_kept(qc):
    """长度 ≥ 600 字 + 信号数 ≤ 2（仅一两个具体细节）→ 给过当模板。"""
    text = (
        "你的任务：审查代码并按以下步骤验证修复结果。\n"
        "要求：\n"
        + "\n".join(f"{i}. 第 {i} 步骤，检查命名 / 风格 / 错误处理 / 性能 / 安全等"
                     for i in range(1, 30))
    )
    assert len(text) >= 600
    passed, reason = is_quality_prompt(text, qc)
    assert passed, f"应通过但被拒：{reason}"


def test_long_oneoff_with_3_signals_rejected(qc):
    """长度即使 > 600 字，含 ≥ 3 个一次性信号（路径 + task ID + 版本号）也拒。"""
    extra = "\n".join(
        f"第 {i} 步：检查某个具体输出，比对前后一致性，记录差异给出结论。"
        for i in range(1, 25)
    )
    text = (
        "看 v1.6 e2e pipeline 日志（task b7a5nv6zh）。读 "
        "C:\\Users\\lin\\AppData\\Local\\Temp\\claude\\D--My-Project-Likner-SGO\\"
        "tasks\\b7a5nv6zh.output 的最后 50 行确认进度。\n\n"
        + extra
    )
    assert len(text) >= 600
    passed, reason = is_quality_prompt(text, qc)
    assert not passed and reason == "oneoff_debug_instruction"


def test_api_key_in_text_rejected(qc):
    """含 API key 的提示词无论多长都拒，避免敏感信息入库。"""
    text = (
        "下一步：用这个 key 测下 E2E：sk-1234567890abcdef1234567890abcdef。"
        "跑完 5 个用例确认正常，然后回报结果。这是一个完整可复用的指令。"
        "需要详细记录每一步的输入输出和验证依据。"
    )
    passed, reason = is_quality_prompt(text, qc)
    assert not passed and reason == "contains_api_key"


# ---------------------------------------------------------------------------
# AI 回复泄漏检测
# ---------------------------------------------------------------------------

def test_ai_response_opener_rejected(qc):
    text = (
        "我会按以下步骤来做这件事情，先把上下文理清楚。\n"
        "我理解你的意思了，这是一个常见问题。\n"
        "OK，让我先看一下这个文件的具体内容，确认它的结构。\n"
        "根据你的描述，问题应该出在第 X 行的某个调用上。\n"
        "让我帮你跑一遍测试，看看实际的错误输出是什么。\n"
        "我会先检查依赖是否正确安装，然后跑 pytest 看哪条失败。\n"
        "我理解了，让我帮你修。\n"
        "OK，让我现在开始动手，先建立一个最小复现。"
    )
    passed, reason = is_quality_prompt(text, qc)
    assert not passed and reason == "looks_like_ai_response"


def test_high_code_block_ratio_rejected(qc):
    text = "看下这段代码片段：\n```python\n" + "print('hello world this is a long line')\n" * 60 + "```\n结束"
    passed, reason = is_quality_prompt(text, qc)
    assert not passed and reason == "looks_like_ai_response"


# ---------------------------------------------------------------------------
# 语言偏好
# ---------------------------------------------------------------------------

def test_pure_english_rejected_when_pref_zh():
    qc = QualityConfig(language_preference="zh")  # 显式中文偏好
    text = (
        "Please review the following code carefully and identify any potential "
        "issues with naming conventions, code style, error handling, performance "
        "and security. Be thorough and provide actionable feedback for each issue. "
        "Also check for race conditions, memory leaks, and inefficient algorithms. "
        "Make sure to consider both functional correctness and non-functional "
        "qualities like maintainability and testability of the code base."
    )
    passed, reason = is_quality_prompt(text, qc)
    assert not passed and "language_pref" in reason


def test_pure_english_kept_when_pref_both():
    qc2 = QualityConfig(language_preference="both")
    text = (
        "Your task: review the following code for issues.\n"
        "Requirements:\n"
        "1. Check naming conventions across the file\n"
        "2. Check code style consistency with the rest of the project\n"
        "3. Check error handling: every external call must have a try/except\n"
        "4. Check performance: flag any O(n^2) loops\n"
        "5. Check security: no SQL string concatenation, no shell injection"
    )
    passed, reason = is_quality_prompt(text, qc2)
    assert passed, reason


def test_chinese_text_kept_when_pref_zh(qc):
    text = (
        "请审查下面这段代码，重点检查命名规范、代码风格、错误处理、性能和安全问题。"
        "对每个问题给出具体的修改建议，不要泛泛而谈。\n要求：\n"
        "1. 必须指出具体行号和文件位置\n"
        "2. 给出修改前后的代码对比示例\n"
        "3. 标注严重程度（高/中/低），并解释为什么\n"
        "4. 性能问题给出 big-O 估算和潜在影响\n"
        "5. 安全问题描述攻击向量"
    )
    passed, reason = is_quality_prompt(text, qc)
    assert passed, f"中文应通过：{reason}"


# ---------------------------------------------------------------------------
# 结构 / 闲聊词
# ---------------------------------------------------------------------------

def test_flow_word_short_message_rejected(qc):
    # 第一行短闲聊词，但内容刚好够长（>=150）—— 仍按 "无结构 + 短" 拒
    text = "继续\n" + "x" * 200
    passed, reason = is_quality_prompt(text, qc)
    # 结构 + 长度逻辑：text 长 200 < 350，且无结构标记 → 拒
    assert not passed


def test_no_structure_no_imperative_long_rejected_as_doc(qc):
    """v0.2 反馈：长度长但全是描述句、无指令性 → 文档碎片，拒入库。

    这种文本看起来像设计笔记 / README 段落，不是用户写的"让 AI 做某事"的提示词。
    """
    sentences = [
        "这是第一句话，描述一些上下文。",
        "接下来谈谈我们要解决的问题是什么。",
        "技术选型上我们考虑了几个方案。",
        "最终决定用 Python 加 PySide6 的桌面方案。",
        "原因是它和现有的工具链一致。",
        "另外 PyInstaller 打包成熟，分发方便。",
        "数据存放在用户本地的 vault 目录。",
        "所有改动都自动 git commit 留底。",
        "这样换电脑时 git clone 一行就能恢复。",
        "整体流程对新手友好，命令行也保留给高级用户。",
    ]
    text = "\n".join(sentences) + "\n" + "\n".join(sentences)
    passed, reason = is_quality_prompt(text, qc)
    assert not passed
    assert reason == "doc_fragment"


def test_long_text_with_imperative_kept(qc):
    """长文本如果含指令性动词（"请审查"/"检查"等）则放过。"""
    text = (
        "请审查下面这段架构设计的可行性，重点检查并发模型和资源管理。\n"
        "技术选型上我们考虑了 Python 加 PySide6 的桌面方案。\n"
        "最终决定用 PyInstaller 打包成熟，分发方便。\n"
        "数据存放在用户本地的 vault 目录，所有改动都自动 git commit 留底。\n"
        "这样换电脑时 git clone 一行就能恢复，整体流程对新手友好。\n"
        "你需要列出三个最大的潜在风险，并对每个给出 mitigation 方案。"
    )
    passed, reason = is_quality_prompt(text, qc)
    assert passed, reason


# ---------------------------------------------------------------------------
# 双信号去重
# ---------------------------------------------------------------------------

def test_dedupe_token_overlap():
    a = "请按以下步骤验证：1. 跑 pytest 2. 跑 ruff 3. 截图"
    b = "请按以下步骤验证：1. 跑 pytest 2. 跑 ruff 3. 截图保存"
    assert quality.is_duplicate(a, b, token_threshold=0.55, seq_threshold=0.80)


def test_dedupe_sequence_match():
    """SequenceMatcher 抓字面相似但 token 集合差异大的情况。"""
    a = "abcdefghij" * 50
    b = "abcdefghij" * 49 + "klmnopqrst"
    assert quality.is_duplicate(a, b, token_threshold=0.99, seq_threshold=0.80)


def test_dedupe_distinct_kept():
    a = "请按以下步骤验证 React 组件：跑测试、截图、对比"
    b = "请按以下步骤迁移 Postgres 数据：备份、停服、迁移、验证、切换"
    assert not quality.is_duplicate(a, b, token_threshold=0.55, seq_threshold=0.80)


def test_dedupe_candidates_keeps_longest():
    items = [
        "短的：playwright 验证 UI",
        "稍长版：playwright 验证 UI 改动，要截图",
        "完整版：playwright 验证 UI 改动，要截图，每条 PR 必须包含截图对比，否则不许合并",
    ]
    kept = quality.dedupe_candidates(items, get_text=lambda x: x,
                                       token_threshold=0.55, seq_threshold=0.80)
    assert len(kept) == 1
    assert "PR 必须" in kept[0]
