"""提示词质量过滤：让挖到的"提示词"真的是用户写的、有用的、可复用的。

V1 实测发现的 5 类噪声：
  1. 乱码 / shell 日志 dump（PowerShell stderr 用 cp936 解码错误后存进 transcript）
  2. 一次性调试指令（"看 v1.6 e2e 日志（task b7a5nv6zh）..."—— 含具体 path/UUID/version，单次用）
  3. AI 回复风格泄漏（user role 但段首多为"我会..."、大段反引号包裹）
  4. 用户主语种不要的（中文用户的纯英文段、英文用户的纯中文段）
  5. 重复——差异极小的提示词重复入库

本模块是 5 层过滤的统一实现。配置项放在 cfg.quality（QualityConfig）。
"""

from __future__ import annotations

import difflib
import re
from dataclasses import dataclass
from typing import Callable, Iterable, TypeVar


# ---------------------------------------------------------------------------
# 配置
# ---------------------------------------------------------------------------

@dataclass
class QualityConfig:
    # 用户实测反馈：默认 both 让大量纯英文文档碎片混入；中文用户应默认 zh
    language_preference: str = "zh"     # zh | en | both
    min_chars: int = 100
    max_chars: int = 4000
    inter_dedupe_token: float = 0.55    # 候选间 token 重合度阈值
    inter_dedupe_seq_ratio: float = 0.80  # 候选间 SequenceMatcher 比阈值
    db_dedupe_token: float = 0.60       # 与库内 token 重合度阈值
    mojibake_strict: bool = True
    # 是否拒绝"文档碎片"（AGENTS.md / 编码规范的章节）。默认开。
    reject_doc_fragments: bool = True


# ---------------------------------------------------------------------------
# 入口：综合判定
# ---------------------------------------------------------------------------

NOISE_PREFIXES = (
    "<system-reminder>", "<command-", "<task-notification>",
    "[Image #", "[image #", "[Image:", "[image:", "[图片", "[Pasted text",
    # Claude Code 跑 !command 时注入的 envelope
    "<local-command-stdout>", "<local-command-stderr>",
    "<bash-input>", "<bash-stdout>", "<bash-stderr>",
    "Caveat:", "Caveat ",
)

# CC / 其他工具注入的 meta 指令短语（出现在任何位置都拒）
_TOOL_META_PHRASES = (
    "messages below were generated by the user while running local commands",
    "DO NOT respond to these messages or otherwise consider them",
    "Note: Reminder system has been removed",
    "<system>",
    "</system>",
)


def is_quality_prompt(text: str, qc: QualityConfig) -> tuple[bool, str | None]:
    """判定一段 user 文本是否值得入库。

    返回 (passed, reason)：reason 是 None 表示通过；否则是拒因短语，便于 dry-run 解释。
    """
    if not text or text.startswith("/"):
        return False, "empty_or_slash_command"
    text = text.strip()

    # 敏感信息（API key）—— 优先级最高，长度无关
    if _API_KEY_RE.search(text):
        return False, "contains_api_key"

    # 图片附件主体 —— 长度无关
    if _is_image_only(text):
        return False, "image_attachment_only"

    n = len(text)
    if n < qc.min_chars:
        return False, f"too_short_{n}_chars"
    if n > qc.max_chars:
        return False, f"too_long_{n}_chars"
    if any(text.startswith(p) for p in NOISE_PREFIXES):
        return False, "noise_prefix"

    # CC/工具的 meta 指令（不仅仅在开头，正文里出现也算）
    if any(phrase in text for phrase in _TOOL_META_PHRASES):
        return False, "tool_meta_injection"

    if _is_mojibake_or_log(text, strict=qc.mojibake_strict):
        return False, "mojibake_or_log_dump"

    if _is_error_log_paste(text):
        return False, "error_log_paste"

    if _is_oneoff_debug(text):
        return False, "oneoff_debug_instruction"

    if _is_ai_response_leak(text):
        return False, "looks_like_ai_response"

    if _violates_language_pref(text, qc.language_preference):
        return False, f"language_pref_{qc.language_preference}"

    if qc.reject_doc_fragments and _is_doc_fragment(text):
        return False, "doc_fragment"

    if not _has_min_structure_or_length(text):
        return False, "no_structure_and_short"

    return True, None


# ---------------------------------------------------------------------------
# 文档碎片识别（AGENTS.md / CLAUDE.md 章节、编码规范、目录树、README 段）
# ---------------------------------------------------------------------------
#
# 这类碎片不是"提示词"，是参考文档。特征：
# - 标题是 AGENTS.md 经典章节（Coding Style、Project Structure 等）
# - 段首是描述句（"This project is..."、"项目使用..."、"目录结构如下..."）
# - 大段目录树字符（├── └── │）
# - 纯陈述无指令动作（不含"你"、"请"、"做"、"按"、"应"等指令词）

_DOC_CHAPTER_TITLES = (
    # AGENTS.md / Cursor Rules 标准章节
    "coding style", "naming conventions", "project structure",
    "module organization", "build commands", "test commands",
    "development commands", "testing guidelines", "commit guidelines",
    "pull request guidelines", "security configuration", "security tips",
    "configuration tips", "code style", "style guide",
    # 项目文档常见章节
    "项目结构", "项目概述", "项目方法论", "目录结构", "组件清单",
    "关键文档", "关键纪律", "关键约束", "关键决策", "工作流",
    "环境变量", "部署", "运维", "高频陷阱", "兼容性",
    "构建", "测试配置", "端口分配",
    # README 类章节
    "introduction", "overview", "getting started", "installation",
    "usage", "license", "contributing",
    "简介", "介绍", "安装", "使用", "许可", "贡献",
)

_DOC_PREFIX_PHRASES = (
    "Core package code lives in", "Use Python", "Tests use", "Prefer ",
    "Top-level regression tests", "Generated outputs should stay",
    "Supporting research material", "This file provides",
    "These rules apply to", "Recent history uses",
)

_TREE_CHARS_RE = re.compile(r"[├└│─]")
_IMPERATIVE_WORDS = (
    # 中文指令词
    "你需要", "你要", "你的任务", "请", "按以下", "按下面", "按照",
    "应当", "必须", "禁止", "不要", "确保", "完成", "实现",
    "审查", "检查", "修复", "改写", "列出", "解释", "分析", "对比", "找出",
    # 英文指令词（祈使句常见动词 + Prompt 开头模式）
    "you must", "you should", "you need", "please ", "do not ", "ensure ",
    "make sure", "create ", "build ", "implement ",
    "your task", "your goal", "your job", "task:", "goal:", "objective:",
    "check ", "review ", "find ", "fix ", "list ", "explain ", "analyze ",
    "compare ", "identify ", "write ", "generate ", "produce ", "rewrite ",
    "refactor ", "optimize ", "convert ", "translate ", "summarize ",
)


def _is_doc_fragment(text: str) -> bool:
    """识别 AGENTS.md / CLAUDE.md / README 等文档的章节碎片。

    用户实测反馈：refresh-projects 自动扫项目 .md，把 "Coding Style & Naming Conventions"
    "Project Structure" 等纯陈述章节当提示词入库。这些没有指令性，是参考文档。
    """
    stripped = text.strip()
    first_chunk = stripped[:300].lower()
    n = len(stripped)

    # 1. 目录树字符 ≥ 5 个 → 八成是目录结构粘贴
    if len(_TREE_CHARS_RE.findall(stripped[:1500])) >= 5:
        return True

    # 2. 段首匹配文档前缀（纯英文文档专用判定）
    head_line = stripped.splitlines()[0].strip() if stripped.splitlines() else ""
    for prefix in _DOC_PREFIX_PHRASES:
        if first_chunk.startswith(prefix.lower()) or head_line.startswith(prefix):
            return True

    # 3. 章节标题指纹：原文本身或转入库时拼的 title 含已知章节名
    # （这层在 is_quality_prompt 入口走，所以只能从 body 里嗅）
    body_head = first_chunk
    title_hits = sum(1 for t in _DOC_CHAPTER_TITLES if t in body_head)
    if title_hits >= 1:
        # 还得没有指令性才算文档
        if not _has_imperative_voice(stripped):
            return True

    # 4. 长段（≥ 200 字）但无任何指令性动词 → 文档
    if n >= 200 and not _has_imperative_voice(stripped):
        # 排除 code-heavy（代码块占 > 50%）的，那不一定是文档
        code_chars = sum(
            len(line) for line in stripped.splitlines()
            if line.startswith("    ") or line.startswith("\t")
        )
        if code_chars / max(n, 1) < 0.50:
            return True

    return False


def _has_imperative_voice(text: str) -> bool:
    """检测是否有指令性动词（"你"/"请"/"按"/"必须"/"do"/"create" 等）。"""
    low = text.lower()
    return any(w.lower() in low for w in _IMPERATIVE_WORDS)


# ---------------------------------------------------------------------------
# LLM 二次判定（可选）：当规则层放过但用户想更严，调 LLM yes/no
# ---------------------------------------------------------------------------

LLM_JUDGE_SYSTEM_PROMPT = """\
你是提示词审核员。判断下面这段文字是不是"用户写的、可让 AI 复用的提示词"。

是提示词的特征：
- 含明确指令（让 AI 做某事：写代码、审查、改写、列出、解释…）
- 有可复用性（不仅仅描述一次性场景）
- 用户写给 AI 看的（而非 AI 回复 / 项目文档 / 错误日志）

不是提示词的特征：
- AGENTS.md / CLAUDE.md 章节碎片（编码规范、项目结构等）
- README 段落 / 项目介绍
- 错误日志 / shell 输出 / 一次性调试指令
- 目录树 / ASCII 图表
- AI 回复的开头语（"我会…"、"OK, let me…"）

只输出一个字：Y（是提示词）或 N（不是）。不要任何解释。
"""


def llm_judge_is_prompt(cfg, text: str) -> tuple[bool, str]:
    """调 LLM 二次判定（仅在规则层放过 + 用户启用时调）。

    返回 (is_prompt, raw_response)。失败时返回 (True, error)——保守放过避免误删。
    """
    try:
        from . import optimizer
        # 截到前 1200 字给 LLM 判断（节省 token）
        sample = text[:1200]
        result = optimizer._run(
            cfg, sample,
            system_prompt=LLM_JUDGE_SYSTEM_PROMPT,
            mode="auto",
            wrap_user_in_xml=True,
        )
        if not result.success or not result.optimized:
            return True, result.error or "empty"
        verdict = result.optimized.strip().upper()[:5]
        is_prompt = verdict.startswith("Y") or "YES" in verdict
        return is_prompt, verdict
    except Exception as e:
        return True, f"err:{type(e).__name__}"


# ---------------------------------------------------------------------------
# 各层过滤
# ---------------------------------------------------------------------------

# Windows shell 错误在 cp936→UTF-8 错误解码后的特征
_MOJIBAKE_PHRASES = (
    "不是内部或外部命令",
    "鈥檚", "鈥檛",  # 常见 Windows-1252→UTF-8 误解码
    "锛?",  # cp936 中文逗号 mojibake
)
# CJK Extension B 起，常见用户写不出来的"罕用字"集合（mojibake 的高频区域）
_CJK_EXT_RE = re.compile(r"[㐀-䶿]")


def _is_mojibake_or_log(text: str, *, strict: bool = True) -> bool:
    """乱码 / 重复日志 dump 检测。

    判定规则（任一命中即为噪声）：
    1. 已知 shell 错误短语高频（"不是内部或外部命令" 等 ≥ 3 次）
    2. 罕用 CJK Extension B 字符占比过高（mojibake 特征）
    3. **重型重复**：最常见 7 字 phrase 覆盖文本 > 40%（log dump 特征；
       自然中文写作即使有重复段也不会到这个比例）
    """
    # 1. 已知错误短语高频
    for phrase in _MOJIBAKE_PHRASES:
        if text.count(phrase) >= 3:
            return True

    # 2. 罕用 CJK Extension B
    if strict:
        cjk_basic = sum(1 for c in text if "一" <= c <= "鿿")
        cjk_ext = len(_CJK_EXT_RE.findall(text))
        cjk_total = cjk_basic + cjk_ext
        if cjk_total >= 30 and cjk_ext / max(cjk_total, 1) > 0.05:
            return True

    # 3. 重型重复：最常见 7 字 phrase 覆盖文本 > 40%
    sample = text[:1500]
    if len(sample) >= 100:
        seen: dict[str, int] = {}
        max_count = 0
        for i in range(len(sample) - 7 + 1):
            seg = sample[i:i + 7]
            if "\n" in seg or seg.isspace():
                continue
            seen[seg] = seen.get(seg, 0) + 1
            if seen[seg] > max_count:
                max_count = seen[seg]
        if max_count >= 5 and max_count * 7 / len(sample) > 0.40:
            return True

    return False


# 一次性调试指令的特征
_WIN_PATH_RE = re.compile(r"[A-Za-z]:\\(?:[^\\\s\"<>|]+\\){4,}", re.UNICODE)
_BASE32_ID_RE = re.compile(r"\b[a-z][a-z0-9]{6,11}\b")  # 7-12 字符小写字母数字组合
_HEX_ID_RE = re.compile(r"\b[a-f0-9]{8,32}\b")
_VERSION_RE = re.compile(r"\bv\d+\.\d+(\.\d+)?\b")
_DEBUG_KEYWORDS_RE = re.compile(
    r"确认进度|重点验证|schedule\s+\d+\s*分钟|最近\s*\d+\s*行|最新.{0,10}行|"
    r"e2e\s+pipeline|pipeline\s+日志",
    re.IGNORECASE,
)
# API key 泄漏（绝对不入库，避免敏感信息）
_API_KEY_RE = re.compile(
    r"\bsk-[A-Za-z0-9_\-]{20,}|\bAKIA[0-9A-Z]{16}|\bgh[ps]_[A-Za-z0-9]{30,}",
)

# 图片附件标记
_IMAGE_BLOCK_RE = re.compile(r"\[[Ii]mage[^\]]*\]")

# error log / stack trace 粘贴的特征
_ERROR_LOG_PATTERNS = [
    re.compile(r"Error:\s+E[A-Z]+(?:\s|:)"),                 # Node.js: ENOENT/EACCES/EPERM
    re.compile(r"^\s*[Aa]t\s+[A-Za-z]:\\.*?:\d+", re.MULTILINE),  # PS: At D:\path:LN char:N
    re.compile(r"^\+\s+CategoryInfo\b", re.MULTILINE),
    re.compile(r"FullyQualifiedErrorId"),
    re.compile(r"ParserError\b"),
    re.compile(r"PowerShell\s+return\s+code"),
    re.compile(r"Traceback\s+\(most recent call last\)"),
    re.compile(r'^\s+File\s+".*?",\s+line\s+\d+', re.MULTILINE),  # Python stack
    re.compile(r"\berror\s+TS\d+:"),                              # TypeScript
    re.compile(r"^\s*at\s+\w[\w\.]*\s*\(.+:\d+:\d+\)", re.MULTILINE),  # JS stack
    re.compile(r"^\[cmd\]\s", re.MULTILINE),
    re.compile(r"^\s*\+\s*~~~+", re.MULTILINE),                   # PS error pointer ~~~~
    re.compile(r"^\w+:\s+真机调试\s*Error", re.MULTILINE),         # 微信小程序 error 日志
    re.compile(r"openid:\s*[A-Za-z0-9_\-]+|appid:\s*\w+"),         # 微信日志特征
]


def _is_image_only(text: str) -> bool:
    """主体是图片附件标记（含 [Image ...] 块且去掉后剩不到 30 字）→ 拒。"""
    if not _IMAGE_BLOCK_RE.search(text):
        return False
    cleaned = _IMAGE_BLOCK_RE.sub("", text).strip()
    return len(cleaned) < 30


def _is_error_log_paste(text: str) -> bool:
    """用户从控制台粘贴的 error / stack trace 日志（不是真要复用的提示词）。

    判定：≥ 2 个 error log 模式命中 → 拒。
    （单个命中可能是模板里提到错误名，2 个以上才像真的粘了一段栈）
    """
    hits = sum(1 for p in _ERROR_LOG_PATTERNS if p.search(text))
    return hits >= 2


def _is_oneoff_debug(text: str) -> bool:
    """一次性调试指令检测。

    判定（放宽后，只拒最明显的一次性指令）：
    - 含 API key → 直接拒（任何长度）
    - 信号数 ≥ 3 且长度 < 800 → 拒（短到中等长度 + 多种具体痕迹 = 真一次性）
    - 信号数 ≥ 4 → 拒（长度无关；4+ 信号几乎不可能是模板）
    单个或两个信号一律放过（容错给用户）。
    """
    if _API_KEY_RE.search(text):
        return True

    signals = 0
    if _WIN_PATH_RE.search(text):
        signals += 1
    if _BASE32_ID_RE.search(text) and re.search(r"\btask\s|（task\b", text, re.IGNORECASE):
        signals += 1
    if _HEX_ID_RE.search(text):
        signals += 1
    if _VERSION_RE.search(text):
        signals += 1
    if _DEBUG_KEYWORDS_RE.search(text):
        signals += 1

    if signals >= 4:
        return True
    if signals >= 3 and len(text) < 800:
        return True
    return False


# AI 回复的开头语和风格特征
_AI_OPENERS = (
    "我会", "我理解", "我已", "OK，让我", "好的，让我", "根据你的", "根据上述",
    "让我帮你", "让我们", "Let me", "I'll ", "I will ", "I'll go ", "Sure, ",
    "Here's", "Here is",
)


def _is_ai_response_leak(text: str) -> bool:
    """user 消息但风格像 AI 回复。"""
    lines = [line.strip() for line in text.splitlines() if line.strip()]
    if len(lines) < 2:
        return False

    # 段首多为 AI opener
    ai_lines = sum(1 for line in lines if any(line.startswith(o) for o in _AI_OPENERS))
    if ai_lines >= 3 and ai_lines / len(lines) > 0.30:
        return True

    # 代码块占比 > 70%
    in_code = False
    code_chars = 0
    for line in text.splitlines():
        s = line.strip()
        if s.startswith("```"):
            in_code = not in_code
            continue
        if in_code:
            code_chars += len(line)
    if code_chars / max(len(text), 1) > 0.70:
        return True

    # ✓✅ 列表项密度高
    list_lines = [line for line in lines if line[:2] in ("- ", "* ") or line[0] in "•✓✅☑"]
    if list_lines:
        check_lines = sum(
            1 for line in list_lines
            if any(c in line[:5] for c in "✓✅☑")
        )
        if check_lines / len(list_lines) > 0.70 and len(list_lines) >= 3:
            return True

    return False


def _violates_language_pref(text: str, pref: str) -> bool:
    """主语种过滤（放宽后只拒纯外语长段）。"""
    if pref == "both":
        return False
    cjk_count = sum(1 for c in text if "一" <= c <= "鿿")
    ascii_letters = sum(1 for c in text if c.isascii() and c.isalpha())
    total = cjk_count + ascii_letters
    if total < 50:
        return False  # 太短判不出主语种
    cjk_ratio = cjk_count / total
    if pref == "zh":
        # 中文用户：纯英文且长度可观才拒（CJK 几乎为 0 + 至少 150 个英文字母）
        return cjk_ratio < 0.02 and ascii_letters > 150
    if pref == "en":
        return cjk_ratio > 0.70
    return False


# ---------------------------------------------------------------------------
# 结构 / 闲聊词过滤（来自旧 _is_quality_prompt 的逻辑）
# ---------------------------------------------------------------------------

_STRUCT_PATTERNS = [
    re.compile(r"^\s*[-*]\s+", re.MULTILINE),
    re.compile(r"^\s*\d+[\.、]\s+", re.MULTILINE),
    re.compile(r"```"),
    re.compile(r"<task>|<context>|<constraints>|<output_format>", re.IGNORECASE),
    re.compile(r"你的任务|按以下步骤|你需要|要求如下|请按照|step\s*\d", re.IGNORECASE),
]

_FLOW_WORDS = (
    "继续", "嗯", "好", "好的", "ok", "OK", "可以", "对的", "不对", "再来",
    "不要", "不行", "再说", "嗯嗯", "知道了", "明白", "请",
)


def _has_min_structure_or_length(text: str) -> bool:
    """要么有结构标记，要么够长。同时排除"嗯/好"开头的闲聊。

    放宽规则：
    - 中文密度高，一句话 100 字就算合格内容
    - 英文 / 拉丁字母为主时阈值放宽到 180
    """
    first_line = text.splitlines()[0].strip() if text.splitlines() else ""
    if first_line and len(first_line) < 8 and any(first_line.startswith(w) for w in _FLOW_WORDS):
        return False
    structure_count = sum(1 for p in _STRUCT_PATTERNS if p.search(text))
    if structure_count >= 1:
        return True
    cjk_count = sum(1 for c in text if "一" <= c <= "鿿")
    if cjk_count >= 80:  # 中文 ≥ 80 字 ≈ 完整一句话指令
        return True
    return len(text) >= 180


# ---------------------------------------------------------------------------
# 去重：双信号（token 重合 + SequenceMatcher）
# ---------------------------------------------------------------------------

T = TypeVar("T")

_TOKEN_RE = re.compile(r"[A-Za-z]{3,}|[一-鿿]{2,}")


def token_set(text: str) -> set[str]:
    return {t for t in _TOKEN_RE.findall(text.lower())}


def is_duplicate(
    a: str,
    b: str,
    *,
    token_threshold: float,
    seq_threshold: float,
) -> bool:
    """两条提示词是否近似重复。token 重合或 SequenceMatcher 任一命中即判重。"""
    ta = token_set(a)
    tb = token_set(b)
    if ta and tb:
        overlap = len(ta & tb) / max(min(len(ta), len(tb)), 1)
        if overlap >= token_threshold:
            return True
    # SequenceMatcher 慢，截到前 800 字
    sm = difflib.SequenceMatcher(None, a[:800], b[:800])
    return sm.ratio() >= seq_threshold


def dedupe_candidates(
    items: Iterable[T],
    get_text: Callable[[T], str],
    *,
    token_threshold: float = 0.55,
    seq_threshold: float = 0.80,
) -> list[T]:
    """候选间去重；同源候选保留长度最大的。"""
    kept: list[tuple[T, str]] = []
    for item in items:
        text = get_text(item)
        merged = False
        for i, (existing, existing_text) in enumerate(kept):
            if is_duplicate(
                text, existing_text,
                token_threshold=token_threshold,
                seq_threshold=seq_threshold,
            ):
                if len(text) > len(existing_text):
                    kept[i] = (item, text)
                merged = True
                break
        if not merged:
            kept.append((item, text))
    return [it for it, _ in kept]
